version: "2"
plugins:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  nodesecurity:
    enabled: true
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
exclude_patterns:
- bin/
- config/
- db/
- spec/
- lib/
